# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER_NAME = 'mlabouriS'
SERVER_IP = '192.168.56.110'
AGENT_NAME = 'mlabouriSW'
AGENT_IP = '192.168.56.111'

MEM = 1024
CPU = 1
BOX = "debian/bookworm64"

K3S_TOKEN = ENV["P1__K3S_TOKEN"] || "unsecuretoken"

Vagrant.configure("2") do |config|
 	# Generic settings
	config.vm.box = BOX
	config.vm.synced_folder '.', '/vagrant', disabled: true
	config.vm.boot_timeout = 1200
	config.vm.provider "virtualbox" do |vb|
		vb.memory = MEM
		vb.cpus = CPU
	end

	# Pre provision script
	config.vm.provision "shell", path: "scripts/prep.sh", env: {
		SERVER__NAME:SERVER_NAME,
		SERVER__IP:SERVER_IP,
		AGENT__NAME:AGENT_NAME,
		AGENT__IP:AGENT_IP
	}
	
	#Server
	
